name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azurerm_resource_group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "09767b2e-814b-4d1e-a10a-86fcac305dee" \
            --ARM_CLIENT_SECRET "bjG8Q~XGMMscnIUG_nJzQdS4bE2vP1pBSf5ASa42" \
            --tenant "45079bb7-e7a0-49e5-bac0-8a65f3b2946c"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "0e4b359f-769c-4908-9180-91beab7e2ebf"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: azurerm_resource_group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "09767b2e-814b-4d1e-a10a-86fcac305dee" \
            --password "bjG8Q~XGMMscnIUG_nJzQdS4bE2vP1pBSf5ASa42" \
            --tenant "45079bb7-e7a0-49e5-bac0-8a65f3b2946c"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "0e4b359f-769c-4908-9180-91beab7e2ebf"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan